src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FormationRepository;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
#[ORM\Table(name: "tbl_formation")]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?int $capacity = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\ManyToOne(inversedBy: 'formations')]
    private ?User $speaker = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'formationsCreatedBy')]
    private ?User $createdBy = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $startDateTime = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $endDateTime = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_file_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSpeaker(): ?User
    {
        return $this->speaker;
    }

    public function setSpeaker(?User $speaker): self
    {
        $this->speaker = $speaker;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDateTime(): ?\DateTimeImmutable
    {
        return $this->startDateTime;
    }

    public function setStartDateTime(?\DateTimeImmutable $startDateTime): self
    {
        $this->startDateTime = $startDateTime;

        return $this;
    }

    public function getEndDateTime(): ?\DateTimeImmutable
    {
        return $this->endDateTime;
    }

    public function setEndDateTime(?\DateTimeImmutable $endDateTime): self
    {
        $this->endDateTime = $endDateTime;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->image_file_name;
    }

    public function setImageFileName(?string $image_file_name): self
    {
        $this->image_file_name = $image_file_name;

        return $this;
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
            ->add('capacity')
            ->add('price')
            ->add('createdAt')
            ->add('startDate')
            ->add('endDate')
            ->add('description')
            ->add('speaker')
            ->add('createdBy')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use TCPDF;
use DateTimeImmutable;
use App\Entity\Formation;
use App\Form\Formation1Type;
use App\Services\ImageUploaderHelper;
use App\Repository\FormationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/formation')]
class FormationController extends AbstractController
{
    #[Route('/pdf/{id}', name: 'app_formation_pdf', methods: ['GET'])]
    public function pdf(Formation $formation): Response
    {
        $pdf = new TCPDF();

        $left_column = '<img src="images/fcpro.jpg">' . 'Tarif : ' . $formation->getPrice() . ' €' . '<br><br>' . 'Places : ' . $formation->getCapacity();
        $right_column = '<b><u>Description de la formation : </u></b><br><br>' . $formation->getDescription() . '<br><br><br>' . '<b><u>Contenu de la formation : </u></b>' . $formation->getContent();
        $y = $pdf->getY();
        $middle = $pdf->getPageWidth() / 2;
        $name = '<b><i>' . $formation->getName() . '</i></b>';

        $pdf->SetAuthor('SIO1-Team');

        $pdf->SetTitle($formation->getName());
        $pdf->setCellPaddings(1, 1, 1, 1);
        $pdf->setCellMargins(1, 1, 1, 1);

        $pdf->AddPage();

        $pdf->setXY(10, 1);
        $pdf->SetFont('helvetica', '', 9);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->writeHTMLCell(125, '', '', $y, 'Date de création : 01/01/2023', 0, 0, 1, true, 'J', true);

        $pdf->setXY($middle, 1);
        $pdf->SetFont('helvetica', '', 9);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->writeHTMLCell(125, '', '', $y, 'Date de mise à jour : 01/01/2023', 0, 0, 1, true, 'J', true);

        $pdf->setXY($middle-30, 15);
        $pdf->SetFont('helvetica', '', 18);
        $pdf->SetTextColor(1, 14, 51);
        $pdf->SetFillColor(212, 225, 237);
        $pdf->writeHTMLCell(125, '', '', $y, $name, 0, 0, 1, true, 'J', true);

        $pdf->SetFillColor(234, 232, 232);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->setXY(10, 15);
        $pdf->writeHTMLCell(60, '', '', $y, $left_column, 0, 0, 1, true, 'J', true);

        $pdf->SetFont('helvetica', '', 9);
        $pdf->setXY($middle-30, 30);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->writeHTMLCell(125, '', '', $y, $right_column, 0, 0, 1, true, 'J', true);


        return $pdf->Output('fcpro-formation-' . $formation->getId() . '.pdf', 'I');
    }

    #[Route('/{id}/duplicate', name: 'app_formation_duplicate', methods: ['GET', 'POST'])]
    public function duplicate(Request $request, FormationRepository $formationRepository, TranslatorInterface $translator, Formation $formation): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $formation2 = new Formation();
        $formation2->setCreatedAt($formation->getCreatedAt());
        $formation2->setCreatedBy($formation->getCreatedBy());
        $formation2->setContent($formation->getContent());
        $formation2->setDescription($formation->getDescription());

        $formation2->setCapacity($formation->getCapacity());
        $formation2->setStartDateTime($formation->getStartDateTime());
        $formation2->setEndDateTime($formation->getEndDateTime());
        $formation2->setImageFileName($formation->getImageFileName());
        $formation2->setName($formation->getName());
        $formation2->setPrice($formation->getPrice());

        $formationRepository->save($formation2, true);
        $this->addFlash('success', $translator->trans('The formation is copied'));

        return $this->redirectToRoute('app_formation_index');
    }

    /* #[Route('/futur', name: 'app_formation_futur', methods: ['GET'])]
    public function futur(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/futur.html.twig', [
            'formations' => $formationRepository->findAllInTheFuture(),
        ]);
    }
    */

    #[Route('/futur', name: 'app_formation_futur', methods: ['GET'])]
    public function futur(FormationRepository $formationRepository): Response
    {
        $formationsPerThree = array();

        $formations = $formationRepository->findThreeInTheFuture();

        $i=1; $j=0;
        foreach ($formations as $formation) {
            $i++;
            if ($i>3) {
                $j++; $i=1;
            }
            $formationsPerThree[$j][$i] = $formation;
        }
        dump($formations);
        dump($formationsPerThree);
        
        return $this->render('formation/futur.html.twig', ['formationsPerThree' => $formationsPerThree,]);
    }

    #[Route('/catalog', name: 'app_formation_catalog', methods: ['GET'])]
    public function catalog(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/catalog.html.twig', [
            'formations' => $formationRepository->findAllInTheFuture(),
        ]);
    }

    #[Route('/', name: 'app_formation_index', methods: ['GET'])]
    public function index(FormationRepository $formationRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_formation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ImageUploaderHelper $imageUploaderHelper, FormationRepository $formationRepository, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $formation = new Formation();
        $formation->setCreatedAt(new DateTimeImmutable());
        $formation->setCreatedBy($this->getUser());

        $form = $this->createForm(Formation1Type::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $errorMessage = $imageUploaderHelper->uploadImage($form, $formation);
            if (!empty($errorMessage)) {
                $this->addFlash ('danger', $translator->trans('An error has occured: ') . $errorMessage);
            }
            $formationRepository->save($formation, true);

            //return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formation_show', methods: ['GET'])]
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_formation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ImageUploaderHelper $imageUploaderHelper, FormationRepository $formationRepository, Formation $formation, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        $form = $this->createForm(Formation1Type::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $errorMessage = $imageUploaderHelper->uploadImage($form, $formation);
            if (!empty($errorMessage)) {
                $this->addFlash ('danger', $translator->trans('An error has occured: ') . $errorMessage);
            }
            $formationRepository->save($formation, true);

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formation_delete', methods: ['POST'])]
    public function delete(Request $request, Formation $formation, FormationRepository $formationRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPER_ADMIN');

        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) 
        {
            $formationRepository->remove($formation, true);
        }

        return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('app_formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cette formation ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn btn-danger btn-sm mt-2"><i class="fa-solid fa-trash"></i></button>
</form>

templates/formation/_form.html.twig
{{ form_start(form) }}
    {# {{ form_widget(form.imageFileName) }} #}

    <div class="row">
        <div>
            {{ form_row(form.name) }}
        </div>
        <div>
            {{ form_row(form.description) }}
        </div>
        <div>
            {{ form_row(form.content) }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.capacity) }}
        </div>
        <div class="col">
            {{ form_row(form.price) }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.startDateTime) }}
        </div>
        <div class="col">
            {{ form_row(form.endDateTime) }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.speaker) }}
        </div>
        <div class="col">
            {{ form_row(form.createdBy) }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            <img width="150" height="150" src="{{ asset('uploads/images/' ~ formation.imageFileName) }}">
        </div>
        <div class="col">
            {{ form_row(form.image) }}
        </div>
    </div>

    <button class="btn btn-primary mt-3">{{ button_label|default('Créer') }}</button>
    <a class="btn btn-secondary mt-3" href="{{ path('app_formation_index') }}">Revenir à la liste</a>
{{ form_end(form) }}

templates/formation/catalog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue des formations{% endblock %}

{% block body %}
<h1>Catalogue des formations</h1>
<table class='table'>
    {% for formation in formations %}
    <td>
        <div class="card" style="width: 15rem;">
            <img src="{{ asset('uploads/images/' ~ formation.imageFileName) }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ formation.name }}</h5>
                <p class="card-text"><div class="line-clamp">{{ formation.content|raw }}</div></p>
                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvas-{{ formation.id }}" role="button"
                    aria-controls="offcanvasExample">
                    Détails
                </a>
                <a href="/formation/pdf/{{ formation.id }}" target="_blank" class="btn btn-secondary">PDF</a>
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas-{{ formation.id }}"
                    aria-labelledby="offcanvasExampleLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvas-{{ formation.name }}">{{ formation.name }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <div align='center'>
                            <strong> Dates : </strong>{{ formation.startDateTime ? formation.startDateTime|date('d/m/Y')
                            : '' }} - {{ formation.endDateTime ? formation.endDateTime|date('d/m/Y') : '' }}<br>
                            <hr>
                            <strong> Tarif :</strong> {{ formation.price }}€<br>
                            <hr>
                            <strong> Capacité :</strong> {{ formation.capacity }} personnes.<br>
                            <hr>
                            <strong> Contenu :</strong>{{ formation.content|raw }}<br>
                            <hr>
                            <strong> Description :</strong> {{ formation.description }}<br>
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    <td>


        {% else %}
        <div class="card" aria-hidden="true">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title placeholder-glow">
                    <span class="placeholder col-6"></span>
                </h5>
                <p class="card-text placeholder-glow">
                    <span class="placeholder col-7"></span>
                    <span class="placeholder col-4"></span>
                    <span class="placeholder col-4"></span>
                    <span class="placeholder col-6"></span>
                    <span class="placeholder col-8"></span>
                </p>
                <a class="btn btn-primary disabled placeholder col-6"></a>
            </div>
        </div>
        {% endfor %}
</table>
{% endblock %}

templates/formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formation{% endblock %}

{% block body %}
    <h1>Edit Formation</h1>

    {{ include('formation/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    {{ include('formation/_delete_form.html.twig') }}
{% endblock %}

templates/formation/futur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue des formations
{% endblock %}

{% block body %}
	<style>
		.photo {
			margin: 5px;
			height: 525px;
			object-fit: cover;
			overflow: hidden;
		}

		.photo img {
			width: 100%;
			height: 100%;
			object-fit: cover;
		}
	</style>
	<h1 style="text-align: center;">Formations à venir</h1>

	<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
		<div class="carousel-indicators">
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
		</div>
		<div class="carousel-inner">
			{% for paquetDe3Formations in formationsPerThree %}
				{%if paquetDe3Formations[1] is defined %}
					<div class="carousel-item carousel-fit">
						<img src="/uploads/images/{{ paquetDe3Formations[1].imageFileName }}" class="d-block w-100 photo" alt="1">
						<div class="carousel-caption d-none d-md-block">
							<h5 style="font-size: 22px" class="ch-max-25 bg-dark p-3 text-white bg-opacity-75 rounded">{{ paquetDe3Formations[1].name }}</h5>
							<br>
							<a class="btn btn-primary" href="/formation/{{ paquetDe3Formations[1].id }}" role="button">
								Voir <i class="fa-solid fa-chevron-right fa-2xs"></i>
							</a>
						</div>
					</div>
				{% endif %}
				{%if paquetDe3Formations[2] is defined %}
					<div class="carousel-item active carousel-fit">
						<img src="/uploads/images/{{ paquetDe3Formations[2].imageFileName }}" class="d-block w-100 photo" alt="1">
						<div class="carousel-caption d-none d-md-block">
							<h5 style="font-size: 22px" class="ch-max-25 bg-dark p-3 text-white bg-opacity-75 rounded">{{ paquetDe3Formations[2].name }}</h5>
							<br>
							<a class="btn btn-primary" href="/formation/{{ paquetDe3Formations[2].id }}" role="button">
								Voir <i class="fa-solid fa-chevron-right fa-2xs"></i>
							</a>
						</div>
					</div>
				{% endif %}
				{% if paquetDe3Formations[3] is defined %}
					<div class="carousel-item carousel-fit">
						<img src="/uploads/images/{{ paquetDe3Formations[3].imageFileName }}" class="d-block w-100 photo" alt="1">
						<div class="carousel-caption d-none d-md-block">
							<h5 style="font-size: 22px" class="ch-max-25 bg-dark p-3 text-white bg-opacity-75 rounded">{{ paquetDe3Formations[3].name }}</h5>
							<br>
							<a class="btn btn-primary" href="/formation/{{ paquetDe3Formations[3].id }}" role="button">
								Voir <i class="fa-solid fa-chevron-right fa-2xs"></i>
							</a>
						</div>
					</div>
				{% endif %}
			{% endfor %}
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Previous</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Next</span>
		</button>
	</div>

{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations{% endblock %}

{% block body %}
    <h1>Liste des formations</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                {#<th>Content</th>#}
                {#<th>Capacité</th>#}
                {#<th>Tarif</th>#}
                {#<th>Date de création</th>#}
                {#<th>Description</th>#}
                {#<th>Date de début</th>#}
                {#<th>Date de fin</th>#}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for formation in formations %}
            <tr>
                <td>{{ formation.id }}</td>
                <td>{{ formation.name }}</td>
                {#<td>{{ formation.content }}</td>#}
                {#<td>{{ formation.capacity }}</td>#}
                {#<td>{{ formation.price }}</td>#}
                {#<td>{{ formation.createdAt ? formation.createdAt|date('Y-m-d H:i:s') : '' }}</td>#}
                {#<td>{{ formation.description }}</td>#}
                {#<td>{{ formation.startDateTime ? formation.startDateTime|date('Y-m-d H:i:s') : '' }}</td>#}
                {#<td>{{ formation.endDateTime ? formation.endDateTime|date('Y-m-d H:i:s') : '' }}</td>#}
                <td>
                    <a class="btn btn-secondary btn-sm" href="{{ path('app_formation_show', {'id': formation.id}) }}"><i class="fa-solid fa-eye"></i></a>
                    <a class="btn btn-warning btn-sm" href="{{ path('app_formation_edit', {'id': formation.id}) }}"><i class="fa-solid fa-pen"></i></a>
                    <a class="btn btn-secondary btn-sm" href="{{ path('app_formation_duplicate', {'id': formation.id}) }}"><i class="fa-solid fa-copy"></i></a>
                    {{ include('formation/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Il n'y a aucune formation !</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_formation_new') }}"><i class="fa-solid fa-plus"></i> Nouvelle formation</a>
{% endblock %}

templates/formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formation{% endblock %}

{% block body %}
    <h1>Nouvelle formation</h1>

    {{ include('formation/_form.html.twig') }}

{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation{% endblock %}

{% block body %}
    <h1>Formation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formation.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ formation.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ formation.content|raw }}</td>
            </tr>
            <tr>
                <th>Capacity</th>
                <td>{{ formation.capacity }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ formation.price }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ formation.createdAt ? formation.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ formation.description }}</td>
            </tr>
            <tr>
                <th>StartDateTime</th>
                <td>{{ formation.startDateTime ? formation.startDateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>EndDateTime</th>
                <td>{{ formation.endDateTime ? formation.endDateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

{% endblock %}